import type { JiraProjection } from "./projections"

export const JIRA_FALLBACK_SNAPSHOT = {
  "openCount": 64,
  "byStatus": {
    "In Progress": 38,
    "To Do": 18,
    "In Review": 8,
    "Done": 9
  },
  "issues": [
    {
      "key": "OR-11",
      "summary": "Milestone — Image Factory deterministic production replay",
      "status": "In Progress",
      "statusCategory": "In Progress",
      "priority": "Highest",
      "type": "Epic",
      "parentKey": null,
      "labels": [],
      "browseUrl": "https://espalwebs.atlassian.net/browse/OR-11",
      "updated": null
    },
    {
      "key": "OR-16",
      "summary": "Milestone — Orchy domain-oriented repository reorganization",
      "status": "In Progress",
      "statusCategory": "In Progress",
      "priority": "Medium",
      "type": "Epic",
      "parentKey": null,
      "labels": [],
      "browseUrl": "https://espalwebs.atlassian.net/browse/OR-16",
      "updated": null
    },
    {
      "key": "OR-18",
      "summary": "Milestone — Orchy capability platforms & factory expansion",
      "status": "To Do",
      "statusCategory": "In Progress",
      "priority": "Medium",
      "type": "Epic",
      "parentKey": null,
      "labels": [],
      "browseUrl": "https://espalwebs.atlassian.net/browse/OR-18",
      "updated": null
    },
    {
      "key": "OR-108",
      "summary": "ORCHY-073 — Capture V1 PBR/Icons production repair chains",
      "status": "In Progress",
      "statusCategory": "In Progress",
      "priority": "High",
      "type": "Task",
      "parentKey": null,
      "labels": [],
      "browseUrl": "https://espalwebs.atlassian.net/browse/OR-108",
      "updated": null
    },
    {
      "key": "OR-138",
      "summary": "ORCHY-122 — Real-host specialized runtime and factory certification",
      "status": "To Do",
      "statusCategory": "In Progress",
      "priority": "High",
      "type": "Task",
      "parentKey": null,
      "labels": [],
      "browseUrl": "https://espalwebs.atlassian.net/browse/OR-138",
      "updated": null
    },
    {
      "key": "OR-153",
      "summary": "ORCHY-114 — Real-host full-system certification after repository reorganization",
      "status": "In Review",
      "statusCategory": "In Progress",
      "priority": "Highest",
      "type": "Task",
      "parentKey": null,
      "labels": [],
      "browseUrl": "https://espalwebs.atlassian.net/browse/OR-153",
      "updated": null
    },
    {
      "key": "OR-207",
      "summary": "ORCHY-059.1 — V1 Icons production qualification",
      "status": "In Review",
      "statusCategory": "In Progress",
      "priority": "Highest",
      "type": "Subtask",
      "parentKey": null,
      "labels": [],
      "browseUrl": "https://espalwebs.atlassian.net/browse/OR-207",
      "updated": null
    },
    {
      "key": "OR-236",
      "summary": "Video Factory M6 — DEFERRED host commissioning and real-video validation",
      "status": "To Do",
      "statusCategory": "In Progress",
      "priority": "Medium",
      "type": "Task",
      "parentKey": null,
      "labels": [],
      "browseUrl": "https://espalwebs.atlassian.net/browse/OR-236",
      "updated": null
    },
    {
      "key": "OR-273",
      "summary": "Milestone — Image Factory QA, repair and PBR accuracy hardening",
      "status": "In Progress",
      "statusCategory": "In Progress",
      "priority": "Highest",
      "type": "Epic",
      "parentKey": null,
      "labels": [],
      "browseUrl": "https://espalwebs.atlassian.net/browse/OR-273",
      "updated": null
    },
    {
      "key": "OR-278",
      "summary": "QA-05 — PBR physical plausibility and deterministic reference-render validation",
      "status": "In Review",
      "statusCategory": "In Progress",
      "priority": "Highest",
      "type": "Task",
      "parentKey": null,
      "labels": [],
      "browseUrl": "https://espalwebs.atlassian.net/browse/OR-278",
      "updated": null
    },
    {
      "key": "OR-280",
      "summary": "QA-07 — Empirical threshold calibration and false-accept/false-reject reporting",
      "status": "In Review",
      "statusCategory": "In Progress",
      "priority": "High",
      "type": "Task",
      "parentKey": null,
      "labels": [],
      "browseUrl": "https://espalwebs.atlassian.net/browse/OR-280",
      "updated": null
    },
    {
      "key": "OR-281",
      "summary": "QA-08 — Accuracy certification gate, benchmark deltas and production go/no-go evidence",
      "status": "In Review",
      "statusCategory": "In Progress",
      "priority": "High",
      "type": "Task",
      "parentKey": null,
      "labels": [],
      "browseUrl": "https://espalwebs.atlassian.net/browse/OR-281",
      "updated": null
    },
    {
      "key": "OR-287",
      "summary": "Milestone — Full-stack coverage and Sonar zero-issue hardening",
      "status": "In Progress",
      "statusCategory": "In Progress",
      "priority": "Highest",
      "type": "Task",
      "parentKey": null,
      "labels": [],
      "browseUrl": "https://espalwebs.atlassian.net/browse/OR-287",
      "updated": null
    },
    {
      "key": "OR-290",
      "summary": "QA-GPUV — Pending GPU/real-host accuracy certification",
      "status": "To Do",
      "statusCategory": "In Progress",
      "priority": "High",
      "type": "Subtask",
      "parentKey": null,
      "labels": [],
      "browseUrl": "https://espalwebs.atlassian.net/browse/OR-290",
      "updated": null
    },
    {
      "key": "OR-296",
      "summary": "QA-ALLV — Deferred integrated validation after frozen accuracy hardening",
      "status": "In Progress",
      "statusCategory": "In Progress",
      "priority": "Highest",
      "type": "Task",
      "parentKey": null,
      "labels": [],
      "browseUrl": "https://espalwebs.atlassian.net/browse/OR-296",
      "updated": null
    },
    {
      "key": "OR-300",
      "summary": "QA-07V — Deferred validation for calibration registry and reports",
      "status": "In Progress",
      "statusCategory": "In Progress",
      "priority": "High",
      "type": "Subtask",
      "parentKey": null,
      "labels": [],
      "browseUrl": "https://espalwebs.atlassian.net/browse/OR-300",
      "updated": null
    },
    {
      "key": "OR-301",
      "summary": "QA-08V — Deferred integrated accuracy certification",
      "status": "To Do",
      "statusCategory": "In Progress",
      "priority": "High",
      "type": "Subtask",
      "parentKey": null,
      "labels": [],
      "browseUrl": "https://espalwebs.atlassian.net/browse/OR-301",
      "updated": null
    },
    {
      "key": "OR-336",
      "summary": "SC-05 — Sonar zero actionable issues",
      "status": "In Progress",
      "statusCategory": "In Progress",
      "priority": "Highest",
      "type": "Subtask",
      "parentKey": null,
      "labels": [],
      "browseUrl": "https://espalwebs.atlassian.net/browse/OR-336",
      "updated": null
    },
    {
      "key": "OR-337",
      "summary": "Inherited coverage/Sonar certification debt — close through TEST LAYER 09",
      "status": "In Progress",
      "statusCategory": "In Progress",
      "priority": "Highest",
      "type": "Subtask",
      "parentKey": null,
      "labels": [],
      "browseUrl": "https://espalwebs.atlassian.net/browse/OR-337",
      "updated": null
    },
    {
      "key": "OR-354",
      "summary": "ORCHY-114V — Finish exact-head domain-reorg Image Factory runtime certification",
      "status": "In Progress",
      "statusCategory": "In Progress",
      "priority": "Highest",
      "type": "Subtask",
      "parentKey": null,
      "labels": [],
      "browseUrl": "https://espalwebs.atlassian.net/browse/OR-354",
      "updated": null
    },
    {
      "key": "OR-356",
      "summary": "Milestone — Mission Autotune v3: evidence-driven factory self-improvement",
      "status": "In Progress",
      "statusCategory": "In Progress",
      "priority": "Highest",
      "type": "Epic",
      "parentKey": null,
      "labels": [],
      "browseUrl": "https://espalwebs.atlassian.net/browse/OR-356",
      "updated": null
    },
    {
      "key": "OR-372",
      "summary": "Milestone — Testing assurance 2026: effectiveness, resilience and evidence closure",
      "status": "To Do",
      "statusCategory": "In Progress",
      "priority": "Highest",
      "type": "Epic",
      "parentKey": null,
      "labels": [],
      "browseUrl": "https://espalwebs.atlassian.net/browse/OR-372",
      "updated": null
    },
    {
      "key": "OR-379",
      "summary": "TA26-O07 — Advanced-testing evidence, adoption map and final validation-doc closeout",
      "status": "In Review",
      "statusCategory": "In Progress",
      "priority": "High",
      "type": "Task",
      "parentKey": null,
      "labels": [],
      "browseUrl": "https://espalwebs.atlassian.net/browse/OR-379",
      "updated": null
    },
    {
      "key": "OR-381",
      "summary": "HOST-TA26-O — Host-only advanced assurance on Madriguera",
      "status": "In Progress",
      "statusCategory": "In Progress",
      "priority": "Highest",
      "type": "Task",
      "parentKey": null,
      "labels": [],
      "browseUrl": "https://espalwebs.atlassian.net/browse/OR-381",
      "updated": null
    },
    {
      "key": "OR-385",
      "summary": "MUT-DEBT — ExecutionStore survivors (rebaseline current SHA)",
      "status": "In Progress",
      "statusCategory": "In Progress",
      "priority": "High",
      "type": "Subtask",
      "parentKey": null,
      "labels": [],
      "browseUrl": "https://espalwebs.atlassian.net/browse/OR-385",
      "updated": null
    },
    {
      "key": "OR-387",
      "summary": "MUT-DEBT — MissionSpec survivors (rebaseline current SHA)",
      "status": "In Progress",
      "statusCategory": "In Progress",
      "priority": "High",
      "type": "Subtask",
      "parentKey": null,
      "labels": [],
      "browseUrl": "https://espalwebs.atlassian.net/browse/OR-387",
      "updated": null
    },
    {
      "key": "OR-388",
      "summary": "MUT-DEBT — Mission progression survivors (rebaseline current SHA)",
      "status": "In Progress",
      "statusCategory": "In Progress",
      "priority": "High",
      "type": "Subtask",
      "parentKey": null,
      "labels": [],
      "browseUrl": "https://espalwebs.atlassian.net/browse/OR-388",
      "updated": null
    },
    {
      "key": "OR-399",
      "summary": "HOST-TA26-O07 — Final advanced-assurance evidence reconciliation",
      "status": "To Do",
      "statusCategory": "In Progress",
      "priority": "High",
      "type": "Subtask",
      "parentKey": null,
      "labels": [],
      "browseUrl": "https://espalwebs.atlassian.net/browse/OR-399",
      "updated": null
    },
    {
      "key": "OR-410",
      "summary": "MRPG3-08 — Mission Autotune acceptance, exact-SHA factory qualification and docs reconciliation",
      "status": "In Progress",
      "statusCategory": "In Progress",
      "priority": "Highest",
      "type": "Task",
      "parentKey": null,
      "labels": [],
      "browseUrl": "https://espalwebs.atlassian.net/browse/OR-410",
      "updated": null
    },
    {
      "key": "OR-441",
      "summary": "Mission Scientist demand-managed LLM runtime — real-host acceptance",
      "status": "In Review",
      "statusCategory": "In Progress",
      "priority": "Highest",
      "type": "Task",
      "parentKey": null,
      "labels": [],
      "browseUrl": "https://espalwebs.atlassian.net/browse/OR-441",
      "updated": null
    },
    {
      "key": "OR-447",
      "summary": "Mission Core — cross-domain self-improvement control plane",
      "status": "In Progress",
      "statusCategory": "In Progress",
      "priority": "Highest",
      "type": "Epic",
      "parentKey": null,
      "labels": [],
      "browseUrl": "https://espalwebs.atlassian.net/browse/OR-447",
      "updated": null
    },
    {
      "key": "OR-453",
      "summary": "Deep Research Mission adapter — active-learning self-improvement loop",
      "status": "In Progress",
      "statusCategory": "In Progress",
      "priority": "Highest",
      "type": "Task",
      "parentKey": null,
      "labels": [],
      "browseUrl": "https://espalwebs.atlassian.net/browse/OR-453",
      "updated": null
    },
    {
      "key": "OR-457",
      "summary": "Rotate exposed cloud-runner credentials after onboarding",
      "status": "To Do",
      "statusCategory": "In Progress",
      "priority": "High",
      "type": "Task",
      "parentKey": null,
      "labels": [],
      "browseUrl": "https://espalwebs.atlassian.net/browse/OR-457",
      "updated": null
    },
    {
      "key": "OR-479",
      "summary": "Qualify Azure Pipelines Free runner when Microsoft account is unblocked",
      "status": "To Do",
      "statusCategory": "In Progress",
      "priority": "Medium",
      "type": "Task",
      "parentKey": null,
      "labels": [],
      "browseUrl": "https://espalwebs.atlassian.net/browse/OR-479",
      "updated": null
    },
    {
      "key": "OR-481",
      "summary": "Offload SonarScanner and coverage analysis to Buildkite Hosted",
      "status": "In Progress",
      "statusCategory": "In Progress",
      "priority": "High",
      "type": "Task",
      "parentKey": null,
      "labels": [],
      "browseUrl": "https://espalwebs.atlassian.net/browse/OR-481",
      "updated": null
    },
    {
      "key": "OR-495",
      "summary": "Milestone — Agentic Coding reconciliation: lean execution loop and New Task recovery",
      "status": "To Do",
      "statusCategory": "In Progress",
      "priority": "Highest",
      "type": "Epic",
      "parentKey": null,
      "labels": [],
      "browseUrl": "https://espalwebs.atlassian.net/browse/OR-495",
      "updated": null
    },
    {
      "key": "OR-504",
      "summary": "AGREC-09 P1 — Frozen benchmark, exact-SHA certification and final documentation reconciliation",
      "status": "In Review",
      "statusCategory": "In Progress",
      "priority": "High",
      "type": "Task",
      "parentKey": null,
      "labels": [],
      "browseUrl": "https://espalwebs.atlassian.net/browse/OR-504",
      "updated": null
    },
    {
      "key": "OR-515",
      "summary": "Milestone — Recursive Mission Self-Improvement v1 (near-singularity)",
      "status": "To Do",
      "statusCategory": "In Progress",
      "priority": "Highest",
      "type": "Epic",
      "parentKey": null,
      "labels": [],
      "browseUrl": "https://espalwebs.atlassian.net/browse/OR-515",
      "updated": null
    },
    {
      "key": "OR-518",
      "summary": "RSI-03 P0 — Real recursive Mission qualification (3 generations)",
      "status": "In Progress",
      "statusCategory": "In Progress",
      "priority": "Highest",
      "type": "Task",
      "parentKey": null,
      "labels": [],
      "browseUrl": "https://espalwebs.atlassian.net/browse/OR-518",
      "updated": null
    },
    {
      "key": "OR-521",
      "summary": "Milestone — Agentic Coding 16GB efficiency + runtime selection v2",
      "status": "To Do",
      "statusCategory": "In Progress",
      "priority": "Highest",
      "type": "Epic",
      "parentKey": null,
      "labels": [],
      "browseUrl": "https://espalwebs.atlassian.net/browse/OR-521",
      "updated": null
    },
    {
      "key": "OR-524",
      "summary": "AG16-03 P0 — 16 GB local model + vLLM memory qualification",
      "status": "In Progress",
      "statusCategory": "In Progress",
      "priority": "Highest",
      "type": "Task",
      "parentKey": null,
      "labels": [],
      "browseUrl": "https://espalwebs.atlassian.net/browse/OR-524",
      "updated": null
    },
    {
      "key": "OR-525",
      "summary": "AG16-04 P0 — Current-controller benchmark adapters for Aider, Cline and OpenCode",
      "status": "In Progress",
      "statusCategory": "In Progress",
      "priority": "Highest",
      "type": "Task",
      "parentKey": null,
      "labels": [],
      "browseUrl": "https://espalwebs.atlassian.net/browse/OR-525",
      "updated": null
    },
    {
      "key": "OR-527",
      "summary": "AG16-06 P0 — Strict-parity Aider vs Cline vs OpenCode bake-off",
      "status": "In Progress",
      "statusCategory": "In Progress",
      "priority": "Highest",
      "type": "Task",
      "parentKey": null,
      "labels": [],
      "browseUrl": "https://espalwebs.atlassian.net/browse/OR-527",
      "updated": null
    },
    {
      "key": "OR-528",
      "summary": "AG16-07 P1 — Native-strength optimization lane for eligible runtimes",
      "status": "In Progress",
      "statusCategory": "In Progress",
      "priority": "High",
      "type": "Task",
      "parentKey": null,
      "labels": [],
      "browseUrl": "https://espalwebs.atlassian.net/browse/OR-528",
      "updated": null
    },
    {
      "key": "OR-529",
      "summary": "AG16-08 P1 — ChatGPT reference throughput + local gap analysis",
      "status": "In Progress",
      "statusCategory": "In Progress",
      "priority": "High",
      "type": "Task",
      "parentKey": null,
      "labels": [],
      "browseUrl": "https://espalwebs.atlassian.net/browse/OR-529",
      "updated": null
    },
    {
      "key": "OR-530",
      "summary": "AG16-09 P1 — Evidence-gated runtime/model promotion, rollback and reconciliation",
      "status": "In Progress",
      "statusCategory": "In Progress",
      "priority": "High",
      "type": "Task",
      "parentKey": null,
      "labels": [],
      "browseUrl": "https://espalwebs.atlassian.net/browse/OR-530",
      "updated": null
    },
    {
      "key": "OR-532",
      "summary": "Qualify OCI A1 Always Free as primary durable SonarQube Server host",
      "status": "In Progress",
      "statusCategory": "In Progress",
      "priority": "Medium",
      "type": "Task",
      "parentKey": null,
      "labels": [],
      "browseUrl": "https://espalwebs.atlassian.net/browse/OR-532",
      "updated": null
    },
    {
      "key": "OR-534",
      "summary": "Deferred empirical Mission evidence — drift, freshness and shadow challenger",
      "status": "To Do",
      "statusCategory": "In Progress",
      "priority": "High",
      "type": "Subtask",
      "parentKey": null,
      "labels": [],
      "browseUrl": "https://espalwebs.atlassian.net/browse/OR-534",
      "updated": null
    },
    {
      "key": "OR-535",
      "summary": "Deferred empirical Strategy Lab acceptance — real challenger to next-Mission champion",
      "status": "To Do",
      "statusCategory": "In Progress",
      "priority": "High",
      "type": "Subtask",
      "parentKey": null,
      "labels": [],
      "browseUrl": "https://espalwebs.atlassian.net/browse/OR-535",
      "updated": null
    },
    {
      "key": "OR-548",
      "summary": "RESEARCH-CARRYOVER — Deferred Surfer empirical qualification after repository retirement",
      "status": "To Do",
      "statusCategory": "In Progress",
      "priority": "High",
      "type": "Task",
      "parentKey": null,
      "labels": [],
      "browseUrl": "https://espalwebs.atlassian.net/browse/OR-548",
      "updated": null
    },
    {
      "key": "OR-557",
      "summary": "RREL-08 P1 — Noninteractive Tailscale WIF recovery; remove interactive-auth recovery from normal operations",
      "status": "In Progress",
      "statusCategory": "In Progress",
      "priority": "Highest",
      "type": "Task",
      "parentKey": null,
      "labels": [],
      "browseUrl": "https://espalwebs.atlassian.net/browse/OR-557",
      "updated": null
    },
    {
      "key": "OR-590",
      "summary": "TEST LAYER 01 — Fast Web",
      "status": "Done",
      "statusCategory": "Done",
      "priority": "High",
      "type": "Task",
      "parentKey": null,
      "labels": [],
      "browseUrl": "https://espalwebs.atlassian.net/browse/OR-590",
      "updated": null
    },
    {
      "key": "OR-594",
      "summary": "TEST LAYER 02 — Fast Python",
      "status": "Done",
      "statusCategory": "Done",
      "priority": "High",
      "type": "Task",
      "parentKey": null,
      "labels": [],
      "browseUrl": "https://espalwebs.atlassian.net/browse/OR-594",
      "updated": null
    },
    {
      "key": "OR-598",
      "summary": "TEST LAYER 03 — Property / State-machine",
      "status": "Done",
      "statusCategory": "Done",
      "priority": "High",
      "type": "Task",
      "parentKey": null,
      "labels": [],
      "browseUrl": "https://espalwebs.atlassian.net/browse/OR-598",
      "updated": null
    },
    {
      "key": "OR-600",
      "summary": "TEST LAYER 04 — Security",
      "status": "Done",
      "statusCategory": "Done",
      "priority": "High",
      "type": "Task",
      "parentKey": null,
      "labels": [],
      "browseUrl": "https://espalwebs.atlassian.net/browse/OR-600",
      "updated": null
    },
    {
      "key": "OR-601",
      "summary": "TEST LAYER 05 — Fuzz",
      "status": "Done",
      "statusCategory": "Done",
      "priority": "High",
      "type": "Task",
      "parentKey": null,
      "labels": [],
      "browseUrl": "https://espalwebs.atlassian.net/browse/OR-601",
      "updated": null
    },
    {
      "key": "OR-602",
      "summary": "TEST LAYER 06 — Performance",
      "status": "Done",
      "statusCategory": "Done",
      "priority": "High",
      "type": "Task",
      "parentKey": null,
      "labels": [],
      "browseUrl": "https://espalwebs.atlassian.net/browse/OR-602",
      "updated": null
    },
    {
      "key": "OR-603",
      "summary": "TEST LAYER 07 — Portability",
      "status": "Done",
      "statusCategory": "Done",
      "priority": "High",
      "type": "Task",
      "parentKey": null,
      "labels": [],
      "browseUrl": "https://espalwebs.atlassian.net/browse/OR-603",
      "updated": null
    },
    {
      "key": "OR-604",
      "summary": "TEST LAYER 08 — Flakes / Randomized repetition",
      "status": "Done",
      "statusCategory": "Done",
      "priority": "High",
      "type": "Task",
      "parentKey": null,
      "labels": [],
      "browseUrl": "https://espalwebs.atlassian.net/browse/OR-604",
      "updated": null
    },
    {
      "key": "OR-605",
      "summary": "TEST LAYER 09 — Coverage / Static / Sonar",
      "status": "In Progress",
      "statusCategory": "In Progress",
      "priority": "High",
      "type": "Task",
      "parentKey": null,
      "labels": [],
      "browseUrl": "https://espalwebs.atlassian.net/browse/OR-605",
      "updated": null
    },
    {
      "key": "OR-606",
      "summary": "TEST LAYER 10 — Mutation",
      "status": "In Progress",
      "statusCategory": "In Progress",
      "priority": "High",
      "type": "Task",
      "parentKey": null,
      "labels": [],
      "browseUrl": "https://espalwebs.atlassian.net/browse/OR-606",
      "updated": null
    },
    {
      "key": "OR-607",
      "summary": "TEST LAYER 11 — Browser / E2E",
      "status": "Done",
      "statusCategory": "Done",
      "priority": "High",
      "type": "Task",
      "parentKey": null,
      "labels": [],
      "browseUrl": "https://espalwebs.atlassian.net/browse/OR-607",
      "updated": null
    },
    {
      "key": "OR-608",
      "summary": "TEST LAYER 12 — Live Chaos / Soak / Recovery",
      "status": "In Progress",
      "statusCategory": "In Progress",
      "priority": "High",
      "type": "Task",
      "parentKey": null,
      "labels": [],
      "browseUrl": "https://espalwebs.atlassian.net/browse/OR-608",
      "updated": null
    },
    {
      "key": "OR-620",
      "summary": "Milestone — Orchy Operator Dashboard: zero-cost private hosted UI + Notion fallback",
      "status": "In Progress",
      "statusCategory": "In Progress",
      "priority": "Highest",
      "type": "Epic",
      "parentKey": null,
      "labels": [],
      "browseUrl": "https://espalwebs.atlassian.net/browse/OR-620",
      "updated": null
    },
    {
      "key": "OR-635",
      "summary": "Layer 12 cannot start: Madriguera wake unavailable and Tailscale recovery key invalid",
      "status": "In Progress",
      "statusCategory": "In Progress",
      "priority": "High",
      "type": "Subtask",
      "parentKey": null,
      "labels": [],
      "browseUrl": "https://espalwebs.atlassian.net/browse/OR-635",
      "updated": null
    },
    {
      "key": "OR-644",
      "summary": "Layer 10 current target regresses frozen mutation score and survivor ratchets",
      "status": "To Do",
      "statusCategory": "In Progress",
      "priority": "High",
      "type": "Subtask",
      "parentKey": null,
      "labels": [],
      "browseUrl": "https://espalwebs.atlassian.net/browse/OR-644",
      "updated": null
    },
    {
      "key": "OR-647",
      "summary": "OCC-14 — Operator UI parity and platform limitation register",
      "status": "In Progress",
      "statusCategory": "In Progress",
      "priority": "Highest",
      "type": "Task",
      "parentKey": null,
      "labels": [],
      "browseUrl": "https://espalwebs.atlassian.net/browse/OR-647",
      "updated": null
    },
    {
      "key": "OR-648",
      "summary": "Emergency Supabase-independent 12-layer certification sweep",
      "status": "To Do",
      "statusCategory": "In Progress",
      "priority": "Highest",
      "type": "Task",
      "parentKey": null,
      "labels": [],
      "browseUrl": "https://espalwebs.atlassian.net/browse/OR-648",
      "updated": null
    },
    {
      "key": "OR-651",
      "summary": "Milestone — Supabase-free critical path & quota-resilient Orchy",
      "status": "In Progress",
      "statusCategory": "In Progress",
      "priority": "Highest",
      "type": "Epic",
      "parentKey": null,
      "labels": [],
      "browseUrl": "https://espalwebs.atlassian.net/browse/OR-651",
      "updated": null
    },
    {
      "key": "OR-656",
      "summary": "P0 — Prove Supabase is optional and reconcile architecture/ADR/operations contracts",
      "status": "In Progress",
      "statusCategory": "In Progress",
      "priority": "Highest",
      "type": "Task",
      "parentKey": null,
      "labels": [],
      "browseUrl": "https://espalwebs.atlassian.net/browse/OR-656",
      "updated": null
    },
    {
      "key": "OR-661",
      "summary": "Milestone — Astra Medium: intelligence integrity & decision calibration",
      "status": "To Do",
      "statusCategory": "In Progress",
      "priority": "Highest",
      "type": "Epic",
      "parentKey": null,
      "labels": [],
      "browseUrl": "https://espalwebs.atlassian.net/browse/OR-661",
      "updated": null
    },
    {
      "key": "OR-669",
      "summary": "ASTRA-REPAIR P1 — Causal repair routing and verified-case retrieval tournament",
      "status": "In Progress",
      "statusCategory": "In Progress",
      "priority": "High",
      "type": "Subtask",
      "parentKey": null,
      "labels": [],
      "browseUrl": "https://espalwebs.atlassian.net/browse/OR-669",
      "updated": null
    },
    {
      "key": "OR-670",
      "summary": "OCC-15 — Restore authenticated zero-cost hosted operator dashboard on Netlify",
      "status": "In Progress",
      "statusCategory": "In Progress",
      "priority": "Highest",
      "type": "Task",
      "parentKey": null,
      "labels": [],
      "browseUrl": "https://espalwebs.atlassian.net/browse/OR-670",
      "updated": null
    }
  ]
} as const satisfies JiraProjection
export const JIRA_FALLBACK_OBSERVED_AT = "2026-10-01T02:45:00.000Z"
